import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/navbar";
import LoginModal from "./components/modals/login-modal";
import WelcomeModal from "./components/modals/welcome-modal";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Footer from "./components/footer";
import Container from "./components/container";
import { SessionProvider } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Car scout",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SessionProvider>
        <body className={inter.className}>
          <ToastContainer
            position="top-left"
            autoClose={2500}
            hideProgressBar
          />
          <Navbar />
          <LoginModal />
          <WelcomeModal />
          <div className="min-h-screen pt-12 lg:pt-16 bg-[#F4F4F4]">
            <div className="w-full min-h-screen">{children}</div>
            <Container>
              <Footer />
            </Container>
          </div>
        </body>
      </SessionProvider>
    </html>
  );
}
